# Generated by Django 3.2.7 on 2021-09-20 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.IntegerField(blank=True, null=True)),
                ('pr_no', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.DateTimeField(auto_now_add=True)),
                ('schedule_assigned', models.BooleanField(default=False)),
                ('selected_pref', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
    ]
