# Generated by Django 3.2.7 on 2021-09-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_selector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='pref_given',
            field=models.BooleanField(default=False),
        ),
    ]
